### ISSUE TITLE
Intercept <err_needreggenick> from irc and add a helpful message

### ISSUE THREAD

**Issue by Matrixcoffee** [matrix-org/matrix-appservice-irc#445] opened 2017-05-30 17:56 UTC
Which should probably give a brief explanation, and a link for detailed information on why and how to register.

**Comment by uhoreg** [comment] 2017-05-30 17:58
see also #248

**Comment by Kegsay** [comment] 2017-05-31 16:05
Closing as dupe of https://github.com/matrix-org/matrix-appservice-irc/issues/248

**Closed by Kegsay** 2017-05-31 16:05 UTC
