### ISSUE TITLE
Half-broken portals kept alongside plumbed channel

### ISSUE THREAD

**Issue by funderscore1** [matrix-org/matrix-appservice-irc#1814] opened 2024-08-18 12:15 UTC
When an OFTC IRC channel is bridged to a Matrix channel, the OFTC portal will continue existing.

E.g. `#postmarketos` is bridged to `#main:postmarketos.org` and has a portal `#_oftc_#postmarketos:matrix.org`.

When joining said portal, messages sent to that portal will appear to native Matrix as coming from `@_oftc_<localpart>[m]:matrix.org`. E.g. I join `#_oftc_#postmarketos:matrix.org` as `@funderscore:nova.astraltech.org`, messages will be shown to `#main:postmarketos.org` matrix as coming from `@_oftc_funderscore[m]:matrix.org`.

**Comment by Mikaela** [comment] 2024-08-18 12:23
Duplicate of #935 and #1436?

**Closed as completed** 2024-08-18 12:39 UTC
