### ISSUE TITLE
IRC <-> Matrix Permissions Are Horribly Broken

### ISSUE THREAD

**Issue by benrob0329** [matrix-org/matrix-appservice-irc#532] opened 2017-12-20 00:25 UTC
Voiced in IRC -> 1 in Matrix (logical and practical)
OP in IRC -> 50 in Matrix (Not logical, restricts admins and makes things painful as no other settings are changed so you can't actually configure the room)
Mod in IRC -> ??? in Matrix, I honestly don't know because 50 is the default "moderator" type priv level, anything lower is not a "mod" by default.

The bridge should be above admins unless added to an existing channel, OPs should be 100 (or whatever its set to), mods should be 50, and voiced should be the minimum required to send messages.

Matrix's permissions are more than flexible enough to accommodate for this, and it would be a big step forward for the bridge.

**Comment by Mikaela** [comment] 2017-12-20 13:23
I think this is a duplicate of https://github.com/matrix-org/matrix-appservice-irc/issues/408.

Ops cannot be PL100 as it cannot ever be removed and I have no idea what you mean with mods and voices are 1 so that cmode +m can be synced.

**Closed by Mikaela** 2017-12-20 13:23 UTC
