### ISSUE TITLE
Allow to specify bind address for listener

### ISSUE THREAD

**Issue by theChrisliebaer** [matrix-org/matrix-appservice-irc#856] opened 2019-10-30 20:33 UTC
Unless I missed something, it doesn't seem to be possible to make the listener bind to localhost only. While the risks of exposing the bridge on all ports can be mitigated with a firewall, I think that being able to specify the bind address is a common request for every kind of server software.

**Comment by Half-Shot** [comment] 2019-10-31 17:22
Yeah we just fixed this in https://github.com/matrix-org/matrix-appservice-bridge/issues/113

**Comment by Half-Shot** [comment] 2019-11-01 15:52
This is also a dupe of https://github.com/matrix-org/matrix-appservice-irc/issues/95

**Closed by Half-Shot** 2019-11-01 15:52 UTC
