### ISSUE TITLE
New people don't appear on IRC

### ISSUE THREAD

**Issue by wb9688** [matrix-org/matrix-appservice-irc#1080] opened 2020-07-02 14:59 UTC
New people that join #freenode_#newpipe:matrix.org don't appear on the IRC side since a few days.

**Comment by gkeegan** [comment] 2020-07-02 15:32
For more info. 

People join via Matrix. Riot users see that they joined. On IRC there is no join message. The new user can send messages and function normally, but people using pure IRC do not see any of the new user's messages.

Eventually the new user will show as joined on IRC after a long delay. For the most recent case this was either close to or exactly one hour delay.

**Comment by Half-Shot** [comment] 2020-07-04 10:13
This seems pretty serious. Feels kike #940 in the extremes.

**Comment by Bubu** [comment] 2020-07-13 20:27
This has been an occasional problem since basically forever in `#freenode_#fdroid:matrix,org`. I always assumed it was occuring when matrix.org is having slowness periods but I never really followed up on it.

**Comment by emorrp1** [comment] 2020-07-17 13:12
I agree it seems load related - when Element was announced, a few of us had trouble joining rooms over the bridge (including not via federation):

> Hi, I am unable to join https://webchat.freenode.net/#your-land from matrix. !join to the bridge bot creates new room ids, /join syntax joins !tLuBPFbiqCkpkhmnJA:matrix.org but the appservice doesn't join the real channel. It looks like this room was created from wolfe.freenode.net rather than chat.freenode.net but otherwise I can't see a difference from other channels. -- [matrix.to](https://matrix.to/#/!BAXLHOFjvDKUeLafmO:matrix.org/$UIHHvNCGlkVbiUUvvNH7QeO7DdGPD9fMC7+GLdcj06E?via=matrix.org&via=privacytools.io&via=feneas.org)

> How do I message nickserv on Freenode? Tried starting a private chat with @freenode_@nickserv:matrix.org but it never joined the room. -- [matrix.to](https://matrix.to/#/!BAXLHOFjvDKUeLafmO:matrix.org/$XDizOFnUUrhxpov9me9oYSvP2OAs0Rl7FPjqCEhmYnk?via=matrix.org&via=privacytools.io&via=feneas.org)
> nolan: It's @freenode_NickServ:matrix.org - and, IIRC, the capitalization of the name is important.
> I can't do it. Starting a direct chat with that exact ID just creates an empty room. Same for trying to invite it.

> I seem to be unable to join any channels on freenode, maybe related to whatever emorrp1 is experiencing also. I'm new to this so I might be doing something wrong. But I tried both joining with the web-ui for element.io and by sending a !join command to the appservice. And it invited me to the channel but on the IRC side I don't see anyone. -- [matrix.to](https://matrix.to/#/!BAXLHOFjvDKUeLafmO:matrix.org/$8ZdtMuRlPIE48nI5dzfvc9iP+BjhxAgjbsA7CLFApnM?via=matrix.org&via=privacytools.io&via=feneas.org)

**Comment by wb9688** [comment] 2020-07-17 13:19
Another thing I've noticed is that `!whois` for such new users say that they're connected to IRC as some username, but the IRC network says that the username it says isn't connected.

**Comment by wb9688** [comment] 2020-08-14 11:13
#944 seems related, as you get `unsafeClient not ready yet` when trying to `!nick` on `@appservice-irc:matrix.org` while you're a new user that's not visible yet on IRC.

**Comment by Half-Shot** [comment] 2020-08-23 22:09
We think that the root cause was fixed with #1122, which is that username requests were being queued up faster than they could be processed. The bridges will be updated with the fix tomorrow morning.

**Comment by Bubu** [comment] 2020-08-23 22:17
@Half-Shot you linked to the grafana dashboard ticket, I think you meant another one?

**Comment by Half-Shot** [comment] 2020-08-23 23:11
Er yes, edited. Typo :)

**Comment by Bubu** [comment] 2020-09-04 11:53
Saw this again just now on #fdroid:f-droid.org.

**Comment by Half-Shot** [comment] 2020-09-04 13:37
We've just deployed a fix to the matrix.org freenode bridge. Hopefully this is resolved.

**Closed by Half-Shot** 2020-09-04 13:37 UTC
Labels: bug
