### ISSUE TITLE
Multiline replies get cut off

### ISSUE THREAD

**Issue by z3ntu** [matrix-org/matrix-appservice-irc#691] opened 2018-09-21 13:00 UTC
When replying to a message on Matrix and the the reply has e.g. the content
```
first line
second line
```
then it'll look like this (i.e. the second line gets cut off)
![image](https://user-images.githubusercontent.com/3768500/45882358-38d14c80-bdae-11e8-9253-b75350402c6a.png)

Also, reply markers sometimes get sent to IRC and sometimes not, maybe it's intentional but anyways, it doesn't belong into this issue.

**Comment by Mikaela** [comment] 2019-04-20 19:05
I was going to open a duplicate of this before noticing this in related issues and was a click away from it. Below is the text I wrote:

* * * * *

>> how to ban an irc user from an irc channel in which i am op?

> Easy answer: open a real IRC client
Difficult answer: `!cmd <address from !nick here> MODE #channel +b <banmask>`

* https://matrix.to/#/!BAXLHOFjvDKUeLafmO:matrix.org/$/eC/MHWsJvSVBV7sbo0RaYhbm1k2vTZnRBT/Il3kXhM?via=matrix.org&via=privacytools.io&via=ralith.com

What came to IRC:

`2019-04-20T21:57:41+0300 <mikaela[m]2> <charuto "how to ban an irc user from an i"> Easy answer: open a real IRC client`

or with more lines:

```
2019-04-20T21:57:23+0300 <silkeh> Yeah, I think a raw command should work. Something like `!cmd MODE +b *!<user>@<host>`
2019-04-20T21:57:41+0300 <mikaela[m]2> <charuto "how to ban an irc user from an i"> Easy answer: open a real IRC client
2019-04-20T22:00:00+0300 <@Mikaela> hmm, the bridge ate line#2 of my response: Difficult answer; !cmd <address from !nick here> MODE #channel +b <banmask>
```

**Comment by tadzik** [comment] 2021-07-20 15:05
Looks like it's the same issue as https://github.com/matrix-org/matrix-appservice-irc/issues/1198, which will then by fixed by https://github.com/matrix-org/matrix-appservice-irc/pull/1425

**Comment by tadzik** [comment] 2021-07-21 09:41
Should be all good now – please reopen if it comes up again.

**Closed by tadzik** 2021-07-21 09:41 UTC
