### ISSUE TITLE
Matrix user should part IRC channel when unlinking a bridge

### ISSUE THREAD

**Issue by Flexmaen** [matrix-org/matrix-appservice-irc#531] opened 2017-12-14 00:00 UTC
I did test the IRC bridge and linked a Matrix channel to an IRC channel (using the "Manage integrations" function of Riot).

Afterwards I unlinked the channels again and left the Matrix channel with the Matrix user.

The **result** was that the Matrix user still was in the IRC channel. Since the channel was not shown in Riot anymore, i could only leave it by joining and parting again manually, like
/join #freenode_#channame:matrix.org 
/part #freenode_#channame:matrix.org

I think this is not an optimal behaviour, since the Matrix user might not notice that he still is left in the IRC channel. In the current situation also no one had OP anymore, so that no one could kick the user and get the channel empty. I'd propose that the Matrix user should leave the IRC channel automatically when you unlink a bridge.

This seems a problem of the bridge, see discussions at:
https://matrix.to/#/!SudviOJlimDvrGdFCY:matrix.org/$1513205987584601KCPvz:matrix.org
https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$1513205930582836ccdnW:matrix.org

**Comment by Mikaela** [comment] 2017-12-14 07:58
Duplicate of https://github.com/matrix-org/matrix-appservice-irc/issues/403

**Closed by Mikaela** 2017-12-14 07:58 UTC
