### ISSUE TITLE
users actively reading messages should not be kicked for being idle

### ISSUE THREAD

**Issue by thestinger** [matrix-org/matrix-appservice-irc#1194] opened 2020-11-23 04:02 UTC
Users that are logging into their accounts and reading the messages should not be kicked for idling. Matrix has read receipts and those provide a way to detect that users are *actively* lurking rather than joining the channel and not reading it. It may not currently be possible for the bridge to take advantage of this, in which case the necessary plumbing should be developed to make it possible. This is a serious usability issue and makes the IRC bridge implementation very hostile to users. For our channels, this regularly creates conflict and deters future participation in the community.

As a temporary workaround, the IRC bridge could notify users a week before they're kicked and give them a way to stop themselves from being kicked without publicly posting to the channel. At the moment, users are happily reading the channel and then suddenly get kicked with no warning. This will also make it much clearer to users why they got kicked. The kick message should also make it clearer that it was an automated action by the bridge, not the channel moderators.

A substantial portion of the users on the GrapheneOS channels (#grapheneos:matrix.org and #grapheneos-offtopic:matrix.org) primarily lurk in the channel. Some of these users will occasionally post to the channel despite lurking for long periods of time. Some of the channel regulars take breaks from active participation and then end up coming back to the channel later on. It's common for users to get upset after being kicked and they often think that the channel moderators were responsible. It's not clear to users that this was done automatically and that we don't have a way to disable it as the channel moderators.

We chose to make these bridged channels because the core community was originally on IRC, many people still prefer IRC and we didn't want to split the community based on preferred chat clients / protocols.

It's sad seeing bulk purges of users from the channel including people we know are still actively using it and interested in it. Some of them come back, but many don't. Due to a few serious technical issues like this one, we're considering moving away from Matrix by no longer listing it on our sites. We're looking into bridges with other platforms like Telegram to keep the channel more accessible than IRC. This issue prevents Matrix from serving that role.

**Comment by Half-Shot** [comment] 2020-11-23 10:36
This is actually implemented in https://github.com/matrix-org/matrix-appservice-irc/pull/1152, it's just waiting to be deployed on matrix.org.

**Comment by TimFW** [comment] 2020-12-08 10:25
Is there any expected date for this to be deployed?

Sad its not getting more attention.  Everythings done just spinning waiting to go live.............

**Comment by Half-Shot** [comment] 2020-12-09 11:21
We're working on it. This was deployed to OFTC as a test, but we've encountered some impl issues over at https://github.com/matrix-org/synapse/issues/8903

**Comment by thestinger** [comment] 2021-01-07 18:06
Is the server load created by this going to block deploying it? It's sad seeing round after round of active users kicked from our channel for not sending messages. Maybe we need to make our own server and a new Matrix room where we control the bridge and can disable this.

**Comment by losuler** [comment] 2021-05-05 01:31
> As a temporary workaround, the IRC bridge could notify users a week before they're kicked and give them a way to stop themselves from being kicked without publicly posting to the channel.

Could this be a feasible interim solution?

**Comment by Half-Shot** [comment] 2021-07-19 12:14
We've now deployed this as a test on libera.chat's bridge. So far it seems positive, but we'll need to see.

**Comment by pacien** [comment] 2021-07-19 21:53
Note that relying on the read markers as indicators of activity is probably
going to break after [MSC2285] gets implemented. I expect most users coming
from the IRC world to be willing to disable read receipts the moment it becomes
possible.

[MSC2285]: https://github.com/matrix-org/matrix-doc/pull/2285

**Comment by Half-Shot** [comment] 2021-11-10 10:41
I should have pointed out that it's been on libera for ages with no issues.

**Comment by Half-Shot** [comment] 2021-11-10 10:42
>Note that relying on the read markers as indicators of activity is probably
going to break after MSC2285 gets implemented. I expect most users coming
from the IRC world to be willing to disable read receipts the moment it becomes
possible.

Yeah, it's unfortunate. It's basically impossible for us to figure out if a user is active if they disable all means of us checking. I hold out some hope that one day you can direct presence to the users you want to know about your presence, rather than broadcasting it to everyone. That would solve this problem nicely.

**Comment by thestinger** [comment] 2021-11-10 14:58
Could have the bot warn people 7 days before they get kicked from a network with a command to mark themselves as active on that network.

Note: going to be unsubscribe from the thread since we're now using matterbridge and only have 40 users on the IRC side instead of 350+ since we strongly encouraged everyone to migrate to Matrix.

**Comment by Half-Shot** [comment] 2022-02-09 10:34
I'm going to close this as I don't think we are still missing any active users from our idle tracker.

**Closed by Half-Shot** 2022-02-09 10:34 UTC
Labels: matrix.org-support

**Comment by JigmeDatse** [comment] 2023-05-06 21:27
I just got kicked from a Libera.chat bridged room unexpectedly.  I had read up to a few days ago, and it was shortly after (like hours after) I think 3 messages for the first time in a while.  This was the Tenacity room.  To me and the admin, it seems to be "unexpected behaviour".

**Comment by Half-Shot** [comment] 2023-05-07 11:46
@JigmeDatse Do you have a rough idea when you read the room and your userID. We can investigate if the bridge is missing read events.
