### ISSUE TITLE
#_gimpnet_#gtk+:matrix.org is an invite only channel but not set so.

### ISSUE THREAD

**Issue by pksadiq** [matrix-org/matrix-appservice-irc#499] opened 2017-08-31 09:15 UTC
When a new user tries to join gtk+ channel on GIMPNet via RIOT, he/she gets kicked saying it is an invite only channel. Once the user gets invitation, he/she seems to be always permitted to join (So I can't know if the issue still exists).

This may be tested by simply clicking https://riot.im/app/#/room/#_gimpnet_#gtk+:matrix.org and trying to join.

This was reported at https://github.com/vector-im/riot-web/issues/4924

**Comment by Mikaela** [comment] 2017-08-31 11:55
I think this is a duplicate of https://github.com/matrix-org/matrix-appservice-irc/issues/334 / https://github.com/matrix-org/matrix-appservice-irc/issues/187 (fix).

I think you might be able to join by saying `!join #gtk+` in direct chat with `@gimpnet-irc:matrix.org` and if you could get an op to visit Matrix, they might be able to allow anyone to join.

* [Wiki page trying to explain IRC ops what is Matrix](https://github.com/matrix-org/matrix-appservice-irc/wiki/Matrix-for-IRC-user)

**Closed by Mikaela** 2017-08-31 11:55 UTC
