### ISSUE TITLE
!cmd is case sensitive

### ISSUE THREAD

**Issue by aidalgol** [matrix-org/matrix-appservice-irc#550] opened 2018-02-09 22:11 UTC
As reported by @Mikaela, the `COMMAND` argument to `!cmd` must be uppercase, even though the IRC protocol itself is (generally) case-insensitive.

**Comment by Mikaela** [comment] 2018-02-11 18:21
Duplicate of https://github.com/matrix-org/matrix-appservice-irc/issues/273 which didn't previously mention !cmd which is why I didn't find it while thinking that this would be a duplicate.

**Closed by Mikaela** 2018-02-11 18:21 UTC
Labels: bug
