### ISSUE TITLE
Missing messages from IRC in matrix room

### ISSUE THREAD

**Issue by NotMyFault** [matrix-org/matrix-appservice-irc#1665] opened 2023-02-21 16:10 UTC
Hey,

Occasionally, I miss a few messages on matrix I have on IRC. For example, the room `#jenkins-infra` on libera.chat, is bridged to https://matrix.to/#/#jenkins-infra:matrix.org via appservice.
On IRC I see all messages:
![Screenshot 2023-02-21 at 17 07 20](https://user-images.githubusercontent.com/13383509/220397925-8e00eb3f-1ef9-45fc-bd36-077279dc7b15.png)
But on matrix, the message from danielbeck is missing:
![Screenshot 2023-02-21 at 17 08 21](https://user-images.githubusercontent.com/13383509/220398201-ace51f20-43d6-4484-b1c6-a78b00e48e95.png)
Is there a reason why this is happening and is there a possibility to show all messages on matrix like on IRC?

Thanks in advance!

**Comment by progval** [comment] 2023-02-21 16:17
Duplicate of #1564, halkeye is a room admin.

The workaround is to ask them to either leave the room, or send `!active` to the appservice (or type something in a bridged room) every month or so.

**Comment by progval** [comment] 2023-02-21 16:29
I see this has been happening to your room for months.

To be notified of this on the Matrix side, you can ask your Matrix client to show you hidden events. In Element, you can access the option by running `/devtools`. It will show a `{ "type": org.matrix.appservice-irc.connection }` event every time it starts (at the time the first message is dropped) or stops dropping a message.

**Comment by NotMyFault** [comment] 2023-02-21 16:58
Thanks for your swift response, I was not aware of that behavior. I let the user know, and they left the room of concern, fingers crossed it helps 🤞🏻

**Closed** 2023-02-24 18:26 UTC
