### ISSUE TITLE
!whois is case-sensitive

### ISSUE THREAD

**Issue by Spydar007** [matrix-org/matrix-appservice-irc#496] opened 2017-08-28 09:17 UTC
The `!whois` command is case-sensitive, and gives `Cannot find nick on whois` when the exact case doesn't exist. Given that all nicks and masks are considered case-insensitive, the matrix `!whois` command should also be.

**Comment by aidalgol** [comment] 2018-02-11 00:21
Is this a duplicate of #273?

**Comment by Mikaela** [comment] 2018-02-11 18:19
Yes.

**Closed by Mikaela** 2018-02-11 18:19 UTC
Labels: bug
