### ISSUE TITLE
Hide WebRTC bots on IRC

### ISSUE THREAD

**Issue by afranke** [matrix-org/matrix-appservice-irc#466] opened 2017-06-29 18:30 UTC
When someone starts a call, a bot joins the room. That bot has a ghost on the IRC side, which is unnecessary. The bridge could “filter it out”.

**Comment by Mikaela** [comment] 2017-06-29 19:12
I think this could possibly be called as duplicate of https://github.com/matrix-org/matrix-appservice-irc/issues/47 which would be a better (or the) solution.

**Comment by Kegsay** [comment] 2017-07-04 14:14
The bridge doesn't know it's a bot, needs additional info from Matrix.

**Comment by Half-Shot** [comment] 2019-11-01 17:07
Closing this as I don't think this is an actionable item. Separately, the verto bridge isn't in use anymore.

**Closed by Half-Shot** 2019-11-01 17:07 UTC
Labels: feature-req, needs-spec
