### ISSUE TITLE
#gnome:gnome.org has some spurious virtual users in it

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-appservice-irc#986] opened 2020-02-15 13:16 UTC
`@_gimpnet_mrmcq2u_:gnome.org` is currently visible on Matrix, but is not joined on the IRC side

**Comment by Exalm** [comment] 2020-02-15 13:18
Same with `@_gimpnet_exalm:gnome.org` and `@_gimpnet_d:gnome.org` in https://gnome.riot.im/#/room/#_gimpnet_#gnome-games:gnome.org

**Comment by ara4n** [comment] 2020-02-15 15:57
seems likely this is the same problem, that switching nick on IRC leaves ghosts scattered around the place - which is in turn https://github.com/matrix-org/matrix-appservice-irc/issues/735

**Comment by erciccione** [comment] 2020-02-15 19:53
Yes, this is basically a duplicate of #735. Freenode users who have been in a Freenode room that are not there anymore for any reason (changed nick or left) are still displayed. It's easy to notice simply comparing the number of users in a freenode room when visited from matrix and when visiting through IRC.

This makes very complicate to send DMs to freenode users, because i first have to log in through IRC to make sure the user is actually in the room, which is very inconvenient.

**Comment by Half-Shot** [comment] 2020-02-19 14:52
I tried to reproduce locally and on gimpnet, and am unable to: I think we're going to need to catch it in the act.

![image](https://user-images.githubusercontent.com/2072976/74845795-69ad0c80-5327-11ea-9e82-bfa99683dd8c.png)

**Comment by Half-Shot** [comment] 2020-03-30 13:45
Not heard any more on this. Going to close.

**Closed by Half-Shot** 2020-03-30 13:45 UTC
Labels: bug, needs-investigation
