### ISSUE TITLE
can not join channel with a / in the channel name via alias

### ISSUE THREAD

**Issue by bit** [matrix-org/matrix-appservice-irc#933] opened 2019-12-22 07:53 UTC
unable to join a channel that contains a /.
i.e. #pan.do/ra on freenode

trying to join via explore i get:

#freenode_#pan.do/ra:matrix.org does not exist.

reloading the riot url https://riot.im/app/#/room/#freenode_#pan.do/ra:matrix.org
another error is shown:

#freenode_#pan.do is not accessible at this time.

Try again later, or ask a room admin to check if you have access.

M_UNKNOWN was returned while trying to access the room. If you think you're seeing this message in error, please submit a bug report.

**Comment by Mikaela** [comment] 2019-12-22 16:38
Duplicate of https://github.com/matrix-org/matrix-appservice-irc/issues/500 (I don't know if anyone ever opened an issue with Riot-Web though, I don't remember doing that at least and I don't understand why this long time afterwards).

Workaround: send a message in direct chat with `@appservice-irc:matrix.org` containing `!join #pan.do/ra`

**Comment by Half-Shot** [comment] 2020-10-27 17:53
I think the `!join` trick is probably going to be our preferred solution. Aliases are tricky.

**Closed by Half-Shot** 2020-10-27 17:53 UTC
