### ISSUE TITLE
Channels with keys are not rejoined on disconnect

### ISSUE THREAD

**Issue by fuzzy76** [matrix-org/matrix-appservice-irc#123] opened 2016-08-04 07:33 UTC
If the connection is recycled (because of bridge, server, etc), the room cannot be reconnected because the bridge will attempt to join without key. It probably need to store the key somewhere.

**Comment by Kegsay** [comment] 2016-08-09 10:28
I don't like the idea of persisting channel keys on disk, but in-memory is probably fine. It's otherwise really annoying to have to constantly enter the key at random intervals.

**Comment by fuzzy76** [comment] 2016-08-09 11:19
The biggest problem here is actually that there is _no_ feedback anywhere. The channel shows up as before, it's just not wired up on the IRC side.

**Comment by Kegsay** [comment] 2016-08-09 14:51
Really? I'm surprised, since we do pass through IRC protocol errors and have personally seen `ERR_BADCHANNELKEY` errors be sent to me by the bridge bot user. Can you elaborate some more please?

**Comment by fuzzy76** [comment] 2016-08-10 06:25
The public freenode bridge was restarted while I did not have any Matrix clients open. When I later opened Vector (via web) all the channels seemed connected (though there was no indication anywhere that the bridge had been restarted). Everything worked, except that my +k channel was suspiciously silent. After a day I decided to try to re-issue !join to the appservice account and suddenly the channel sprang back to life. I connect through my own HS (v15.x - yes I need to upgrade).

**Comment by Kegsay** [comment] 2016-08-10 08:40
Ah, I'm aware of that particular failure mode (starting up doesn't send metadata at all). I had a quick check through the issue list and didn't see it filed, so I've filed it as https://github.com/matrix-org/matrix-appservice-irc/issues/129 - going to close this one now that I know what the problem is. Thanks!

**Closed by Kegsay** 2016-08-10 08:40 UTC
