### ISSUE TITLE
Support automatically authenticating to NickServ

### ISSUE THREAD

**Issue by DemiMarie** [matrix-org/matrix-appservice-irc#1600] opened 2022-08-28 15:11 UTC
**Is your feature request related to a problem? Please describe.**
Reconnection to servers that do not support SASL does not work properly.

**Describe the solution you'd like**
On servers (such as OFTC) where NickServ is the well-known authentication service, the bridge should support authenticating to it automatically.

**Describe alternatives you've considered**
CertFP (#747) would also work, but making it convienient to set up would require issuing the CERTFP command to NickServ automatically.

**Additional context**
This would need to be opt-in, as NickServ is not required to be the well-known authentication service.

**Comment by Half-Shot** [comment] 2022-09-08 16:01
Dupe of https://github.com/matrix-org/matrix-appservice-irc/issues/1483. OFTC auth not working is a known issue.

**Closed by Half-Shot** 2022-09-08 16:01 UTC
