### ISSUE TITLE
Option to completely disable the bridge bot

### ISSUE THREAD

**Issue by pacien** [matrix-org/matrix-appservice-irc#451] opened 2017-06-05 11:33 UTC
https://github.com/matrix-org/matrix-appservice-irc/blob/0.7.2/config.sample.yaml#L111
This may not always be wanted and should thus be made optional.
(some private networks do not allow bots at all)

**Comment by Kegsay** [comment] 2017-06-05 11:42
Dupe of https://github.com/matrix-org/matrix-appservice-irc/issues/330

**Closed by Kegsay** 2017-06-05 11:42 UTC
