### ISSUE TITLE
@appservice:libera.chat won't respond to users

### ISSUE THREAD

**Issue by Diablo-D3** [matrix-org/matrix-appservice-irc#1729] opened 2023-05-31 21:59 UTC
I am on the matrix.org homeserver, and the PM chat is unencrypted; I am otherwise connected to the Libera bridge fine and I can talk in IRC channels.

What other things can I do to debug this?

**Comment by joecool1029** [comment] 2023-06-01 00:34
They know the bridge is having issues: https://status.matrix.org/ (they are finally showing it here now). Always hits when the maintainer is on vacation...

It seems like it's beginning to come back now but if they restarted it it'll be a few hours until it settles.

Possible dupe of: https://github.com/matrix-org/libera-chat/issues/6

**Comment by progval** [comment] 2023-06-01 04:52
That's not the same issue; this one is about the appservice not responding, not IRC messages being dropped.

**Comment by AndrewFerr** [comment] 2023-06-01 19:19
Has this issue persisted for any of you?  At least on my end, the appservice bot is responding well after having redeployed the bridge with some fixes.

**Comment by joecool1029** [comment] 2023-06-01 19:24
It's been working fine on my end for at least 12 hours or so. I run my own homeserver, not on the matrix.org instance.

**Comment by Half-Shot** [comment] 2023-06-02 15:51
I believe the bot is also working, and yeah as mentioned it's not nothing to do with the message drops. Feel free to comment if you're still seeing this, but also check your federation setup.

**Closed as completed by Half-Shot** 2023-06-02 15:51 UTC

**Comment by Diablo-D3** [comment] 2023-06-02 17:32
This issue persists.

**Comment by AndrewFerr** [comment] 2023-06-02 18:15
Our logs show that the bot is responding, and chatting with the bot myself (even when using a matrix.org account) indeed has it answer back.

What command(s) are you trying to send?

**Comment by Diablo-D3** [comment] 2023-06-02 19:20
`!help`

**Comment by Diablo-D3** [comment] 2023-06-03 06:33
So, I figured out what the problem was: the matrix.org homeserver set appservice to ignore for me. I'm not sure what behavior triggered that, and I know I didn't set it to ignore myself.
