### ISSUE TITLE
The Matrix-Libera.Chat bridge only works in one direction

### ISSUE THREAD

**Issue by Nick-Hall** [matrix-org/matrix-appservice-irc#1355] opened 2021-05-28 21:16 UTC
**Describe the bug**
I have the room #gramps:matrix.org bridged to the channel #gramps on libera.chat.

Messages in the matrix room appear in the chat channel, but messages in the channel do not appear in the matrix room.

**To Reproduce**
1. Go to the #gramps channel on libera.chat
2. Type in a message
3. Check that it deosn't appear in the room #gramps:matrix.org

**Expected behavior**
I expect to see messages relayed in both directions.

**Additional context**
The channel also isn't listed in the "Explore public rooms" on matrix when I select the libera.chat server.

**Comment by Half-Shot** [comment] 2021-05-28 22:06
Caused by #1332 , fixed by https://github.com/matrix-org/matrix-appservice-irc/pull/1356. 

We essentially don't join all matrix users to the IRC channel after plumbing which broke them due to the safety net feature. I'm going to close this so that people using libera.chat know that it should be fixed.

**Closed by Half-Shot** 2021-05-28 22:06 UTC

**Comment by jasikpark** [comment] 2021-05-30 05:41
It is not yet fixed, when will #1356 be merged?

**Comment by Half-Shot** [comment] 2021-06-08 10:29
This was additionally fixed by #1369 which was deployed to libera.chat last night
