### ISSUE TITLE
Combination of reply + multiline quoted message gets silently truncated Matrix->IRC

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-appservice-irc#806] opened 2019-09-12 12:11 UTC
<img width="1059" alt="Screenshot 2019-09-12 at 13 10 05" src="https://user-images.githubusercontent.com/1294269/64783051-a990ec00-d55e-11e9-84f3-197fbbadc228.png">

```json
{
  "content": {
    "body": "> <@mozilla_snek:matrix.org> standard \"we own a copy of your messages\" stuff that every hosted service has\n\nto name a counterexample, Slack states:\n\n> Subject to the terms and conditions of the Contract, Customer (for itself and all of its Authorized Users) grants us and the Slack Extended Family a worldwide, non-exclusive, limited term license to access, use, process, copy, distribute, perform, export and display Customer Data, and any Non-Slack Products created by or for Customer, only as reasonably necessary (a) to provide, maintain and update the Services; (b) to prevent or address service, security, support or technical issues; (c) as required by law or as permitted by the Data Request Policy; and (d) as expressly permitted in writing by Customer.",
    "format": "org.matrix.custom.html",
    "formatted_body": "<mx-reply><blockquote><a href=\"https://matrix.to/#/!BiYdVxkdxIgVnhEXVH:matrix.org/$15682608111063236XbmZr:matrix.org?via=matrix.org&via=pixie.town&via=tout.im\">In reply to</a> <a href=\"https://matrix.to/#/@mozilla_snek:matrix.org\">@mozilla_snek:matrix.org</a><br>standard &quot;we own a copy of your messages&quot; stuff that every hosted service has</blockquote></mx-reply><p>to name a counterexample, Slack states:</p>\n<blockquote>\n<p>Subject to the terms and conditions of the Contract, Customer (for itself and all of its Authorized Users) grants us and the Slack Extended Family a worldwide, non-exclusive, limited term license to access, use, process, copy, distribute, perform, export and display Customer Data, and any Non-Slack Products created by or for Customer, only as reasonably necessary (a) to provide, maintain and update the Services; (b) to prevent or address service, security, support or technical issues; (c) as required by law or as permitted by the Data Request Policy; and (d) as expressly permitted in writing by Customer.</p>\n</blockquote>\n",
    "m.relates_to": {
      "m.in_reply_to": {
        "event_id": "$15682608111063236XbmZr:matrix.org"
      }
    },
    "msgtype": "m.text"
  },
  "event_id": "$15682857332566EmRCO:pixie.town",
  "origin_server_ts": 1568285733503,
  "sender": "@joepie91:pixie.town",
  "type": "m.room.message",
  "unsigned": {
    "age": 12390
  },
  "room_id": "!BiYdVxkdxIgVnhEXVH:matrix.org"
}
```

ends up on IRC as:

![multiline fail](https://user-images.githubusercontent.com/1294269/64783131-e5c44c80-d55e-11e9-9ffb-0bc53f6cd8da.png)

**Comment by jplatte** [comment] 2020-02-20 17:56
@Mikaela I can't reproduce #691, but I can reproduce this. Maybe that issue has been fixed?

**Comment by tadzik** [comment] 2021-07-20 15:10
This is also fixed by https://github.com/matrix-org/matrix-appservice-irc/pull/1425 (blockquote makes no difference here).

**Comment by tadzik** [comment] 2021-07-21 09:41
Fixed now – please reopen if it shows up again in some form.

**Closed by tadzik** 2021-07-21 09:41 UTC
Labels: bug
