### ISSUE TITLE
Appservice gives power to users or bots in rooms they have not had power

### ISSUE THREAD

**Issue by jaywink** [matrix-org/matrix-appservice-irc#769] opened 2019-06-28 10:36 UTC
Likely related to FreeNode bridge restart. Noticed in a few channels one Matrix user got power 50 from appservice even though that account has never had power in the room. In another room appservice gave power to the Voyager bot.

![Screenshot from 2019-06-28 13-22-46](https://user-images.githubusercontent.com/1174866/60336544-52409e00-99a9-11e9-9589-d27af9dee4c3.png)

This particular room is `#feneas-bloggers:feneas.org` room ID `!hgwruaEKvAYsJVXLwr:feneas.org`. FreeNode channel is `#feneas-bloggers`.

**Comment by Mikaela** [comment] 2019-06-28 12:44
I think this is likely a duplicate of https://github.com/matrix-org/matrix-appservice-irc/issues/518 . Are there not-Matrix users on the channel and is GUARD set?

**Comment by Half-Shot** [comment] 2019-07-09 09:05
This is certainly #518, and we need to investigate it.

**Closed by Half-Shot** 2019-07-09 09:05 UTC
Labels: bug, needs-investigation
