### ISSUE TITLE
Replies to IRC users look a little broken

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/matrix-appservice-irc#728] opened 2019-02-21 14:47 UTC
![image](https://user-images.githubusercontent.com/1342360/53177149-6afa0b00-35e7-11e9-9498-7da2d0df0cc9.png)

![image](https://user-images.githubusercontent.com/1342360/53177138-63d2fd00-35e7-11e9-9ac3-50efd8b0c6b9.png)

Looks like it's due to user IDs for IRC users being quite long (and getting cut off). Is it possible to use their display name and/or cut off the `freenode_` bit?

**Comment by Fuchs** [comment] 2019-02-21 14:48
sorry if that would be covered by "display name" as I am new to Matrix terminology: I think the IRC bridge should try to use their IRC nick, as this will trigger a highlight, which I assume would be wanted / intended behaviour. Thanks for looking into this!

**Comment by Half-Shot** [comment] 2019-02-21 14:58
The bug is because we don't identify the profile for anoa_matrix and so we fall back to user_id, which sadly is too long. The soln here is to map user_ids to nicks, where possible

**Comment by Mikaela** [comment] 2019-02-21 16:11
Duplicate of https://github.com/matrix-org/matrix-appservice-irc/issues/688?

**Comment by Half-Shot** [comment] 2019-02-23 09:18
Yup

**Closed by Half-Shot** 2019-02-23 09:18 UTC
