### ISSUE TITLE
Difficulties bridging to Libera

### ISSUE THREAD

**Issue by c-x-berger** [matrix-org/matrix-appservice-irc#1351] opened 2021-05-28 00:28 UTC
**Describe the bug**
Attempting to "un-bridge" a room from Freenode and subsequently bridging to Libera results in `Bridge returned HTTP 500 Internal Server Error: Room failed validation. You may be attempting to "double bridge" this room. Error: 2`. (I've also seen it say `Error: 1` at the end.)

The room still shows evidence of the original Freenode bridging, for some unknown reason.

**To Reproduce**
1. Remove Freenode bridge from room.
   * This was described to me by the person responsible as "room info -> add widgets, bridges & bots -> irc -> unlink".
2. Attempt to bridge with libera through Element's integration settings.
3. Observe error.

See [screencast](https://youtu.be/_dLzVOiAxxE) of bridging attempt.

**Expected behavior**
Appservice sends verification/authorization request to IRC side.

**Screenshots**
[Screencast of bridging error.](https://youtu.be/_dLzVOiAxxE)

[Traces of Freenode bridging remain in room state...](https://user-images.githubusercontent.com/43154879/119909732-9cc74e00-bf23-11eb-99de-42972fc9fcf5.png)

**Comment by ojwb** [comment] 2021-05-28 07:35
I'm seeing the same error (`Bridge returned HTTP 500 Internal Server Error: Room failed validation. You may be attempting to "double bridge" this room. Error: 2`) and similar traces of freenode bridging remaining in the room state after removing the freenode bridging with `#xapian:matrix.org`.

Happy to test anything that might be useful.

Thanks for working on this.

**Comment by rubdos** [comment] 2021-05-28 07:54
What helped for me is to bridge again with a random new Freenode channel, wait a few seconds, then unbridge, and then wait until appservice disappears.  For me, @appservice:matrix.org stayed in the room after the first unlinking.

**Comment by Half-Shot** [comment] 2021-05-28 09:21
Thanks for reporting, this is a duplicate of https://github.com/matrix-org/matrix-appservice-irc/issues/1323

**Closed by Half-Shot** 2021-05-28 09:21 UTC
