### ISSUE TITLE
Cannot join channels with slashes (e.g. #r/a/dio on Rizon) using alias

### ISSUE THREAD

**Issue by devnoname120** [matrix-org/matrix-appservice-irc#500] opened 2017-09-09 17:44 UTC
1) Go to `Room directory`.
2) Type `#r/a/dio`
3) Switch to `Rizon` from the dropdown list.
4) Press `join`.

**Result**:
![](http://i.imgur.com/ISqbncA.png)

**Expected**: Successfully connected to a room bridged to the irc channel.

**Comment by Mikaela** [comment] 2017-09-09 17:58
I think this is a Riot issue.

Have you tried `!join #r/a/dio` in direct chat with the appservice (`@rizon-irc:matrix.org` IIRC)?

**Comment by Mikaela** [comment] 2017-09-09 18:14
I was able to join there as described in my previous comment. I am not sure where the issue is, but I agree that you should be able to join the room as you described.

The Gitter bridge requires replacing / eith =2F and doesn't work if there are multiple slashes, but that didn't work with this room ( https://github.com/matrix-org/matrix-appservice-gitter/issues/38 ).

I think this issue should be edited into more generic format as I wasn't able to find anything that this would be duplicate of, but I won't do it now (I am a little ill) or on phone.

**Comment by devnoname120** [comment] 2017-09-10 13:06
I can confirm that typing `!join #r/a/dio` in direct chat works, thank you for the solution.

**Comment by Kegsay** [comment] 2017-09-12 13:58
@Mikaela please file this on the riot-web project then, thanks!

**Closed by Kegsay** 2017-09-12 13:58 UTC
Labels: bug, needs-investigation
