### ISSUE TITLE
Cannot link to a channel with mode +r

### ISSUE THREAD

**Issue by pedro-nonfree** [matrix-org/matrix-appservice-irc#632] opened 2018-08-01 11:20 UTC
When you try integration of matrix channel with IRC if the IRC channel have mode +r you will get an error like

`Bridge returned HTTP 500 Internal Server Error: err_needreggednick`

the bot cannot enter to see who is OP.

Seems that the bot of matrix-appservice-irc is not registered in freenode. Registering it would solve this problem

meantime, as a workaround do this as operator of the target channel:

```
/mode -r
# do the request integration between matrix and IRC
/mode +r
```

**Comment by Mikaela** [comment] 2018-08-01 13:05
Duplicate of https://github.com/matrix-org/matrix-appservice-irc/issues/447

**Closed** 2018-08-01 14:39 UTC
